# This is a basic workflow to help you get started with Actions

name: Install ArgoCD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create argocd k3s namespace
        run: |
          set -euxo pipefail
          export KUBECONFIG="/home/brandon/.kube/config"
          env | grep KUBECONFIG
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          
      - name: Install ArgoCD
        run: |
          set -euxo pipefail
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
      
      - name: K3s port forwarding
        run: |
          set -euxo pipefail
          echo "KUBECONFIG=$KUBECONFIG"
          kubectl port-forward svc/argocd-server -n argocd 8080:443
          argocd admin initial-password -n argocd
       
          
