name: uninstall ArgoCD
on:
  workflow_dispatch:
env: 
  HOMELAB_REPO: ${{secrets.HOMELAB_REPO}}
  KUBECONFIG: ${{secrets.KUBECONFIG}}
jobs:
  pre-check:
    runs-on: self-hosted
    steps:
      - name: Checks ns exists
        run: |
          set -euxo pipefail
          export KUBECONFIG="$KUBECONFIG"
          kubectl get ns | grep argo

  uninstall-argo:
    needs: pre-check
    runs-on: self-hosted
    steps:
      - name: Uninstall argocd
        run: |
          set -euxo pipefail
          sudo rm -f /usr/local/bin/argocd
          export KUBECONFIG="$KUBECONFIG"
          kubectl delete -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl delete namespace argocd
          gh secret delete ARGOCD_ADMIN_PASSWORD --repo "$HOMELAB_REPO" --confirm

        
       
          
